import React, { useState, useRef } from "react";
import { Sparkles, CheckCircle2, MessageSquare, Zap, ShieldCheck, HeartHandshake } from "lucide-react";

function About() {
    const cardRef = useRef(null);
    const [transform, setTransform] = useState("perspective(1000px) rotateX(0deg) rotateY(0deg) scale3d(1, 1, 1)");
    const [glare, setGlare] = useState({ x: 50, y: 50, opacity: 0 });

    const handleMouseMove = (e) => {
        if (!cardRef.current) return;
        const rect = cardRef.current.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        const centerX = rect.width / 2;
        const centerY = rect.height / 2;

        const rotateX = ((y - centerY) / centerY) * -6;
        const rotateY = ((x - centerX) / centerX) * 6;

        setTransform(`perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) scale3d(1.01, 1.01, 1.01)`);
        setGlare({
            x: (x / rect.width) * 100,
            y: (y / rect.height) * 100,
            opacity: 0.25,
        });
    };

    const handleMouseLeave = () => {
        setTransform("perspective(1000px) rotateX(0deg) rotateY(0deg) scale3d(1, 1, 1)");
        setGlare({ x: 50, y: 50, opacity: 0 });
    };

    const highlights = [
        {
            icon: HeartHandshake,
            title: "Direct 1-on-1 Founder Access",
            description: "No account managers or middle layers. You communicate directly with the engineer crafting your product.",
        },
        {
            icon: Zap,
            title: "100% Bespoke Engineering",
            description: "Zero heavy pre-made site builders or template clutter. Every line of code is optimized for performance and speed.",
        },
        {
            icon: ShieldCheck,
            title: "Built for Business Growth",
            description: "We focus on clean typography, intuitive user flows, and conversion metrics that convert visitors into clients.",
        },
    ];

    return (
        <section id="about" className="py-20 sm:py-28 relative">
            {/* Background Ambient Glow */}
            <div className="pointer-events-none absolute bottom-10 right-1/3 h-[400px] w-[400px] rounded-full bg-indigo-500/5 blur-[120px]" />

            <div className="mx-auto grid w-[92%] max-w-7xl gap-12 lg:grid-cols-12 items-center relative z-10">
                {/* Left Side: Human Craft Story */}
                <div className="lg:col-span-5">
                    <div className="inline-flex items-center gap-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-3.5 py-1 text-xs font-semibold uppercase tracking-widest text-cyan-300 mb-4 backdrop-blur-md">
                        <Sparkles className="h-3.5 w-3.5" />
                        <span>Why Work With Us</span>
                    </div>

                    <h2 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white leading-[1.15]">
                        Crafted by humans, engineered for impact.
                    </h2>

                    <p className="mt-5 text-base sm:text-lg leading-relaxed text-white/60">
                        At PRAVORA, we believe great digital experiences aren't generated by cookie-cutter templates. They are meticulously designed, coded by hand, and tailored around your real business goals.
                    </p>

                    {/* Human Trust Badge */}
                    <div className="mt-8 flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur-md">
                        <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-tr from-cyan-400 to-indigo-500 text-black font-extrabold shadow-md">
                            100%
                        </div>
                        <div>
                            <h4 className="text-sm font-bold text-white">Custom Handcrafted Code</h4>
                            <p className="text-xs text-white/60">Zero site builders • Maximum speed & SEO</p>
                        </div>
                    </div>
                </div>

                {/* Right Side: Simple 3D Glass Card */}
                <div className="lg:col-span-7">
                    <div
                        ref={cardRef}
                        onMouseMove={handleMouseMove}
                        onMouseLeave={handleMouseLeave}
                        className="group relative overflow-hidden rounded-3xl border border-white/15 bg-gradient-to-b from-white/10 via-black/80 to-zinc-950 p-6 sm:p-10 backdrop-blur-xl transition-all duration-300 shadow-[0_20px_50px_rgba(0,0,0,0.7),inset_0_1px_1px_rgba(255,255,255,0.2)] hover:border-cyan-400/40"
                        style={{
                            transform,
                            transformStyle: "preserve-3d",
                        }}
                    >
                        {/* 3D Glare Light */}
                        <div
                            className="pointer-events-none absolute inset-0 transition-opacity duration-300 z-10"
                            style={{
                                background: `radial-gradient(circle at ${glare.x}% ${glare.y}%, rgba(255, 255, 255, 0.2) 0%, transparent 60%)`,
                                opacity: glare.opacity,
                            }}
                        />

                        <div className="space-y-8 relative z-20">
                            {highlights.map((item, idx) => {
                                const Icon = item.icon;
                                return (
                                    <div
                                        key={item.title}
                                        className="flex gap-5 border-b border-white/10 pb-8 last:border-b-0 last:pb-0 group/item"
                                        style={{ transform: `translateZ(${(idx + 1) * 10}px)` }}
                                    >
                                        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-white/15 bg-white/5 text-cyan-400 group-hover/item:border-cyan-400/50 group-hover/item:bg-cyan-400 group-hover/item:text-black transition-all duration-300 shadow-md">
                                            <Icon className="h-6 w-6" />
                                        </div>

                                        <div>
                                            <h3 className="text-lg sm:text-xl font-bold text-white group-hover/item:text-cyan-300 transition-colors">
                                                {item.title}
                                            </h3>
                                            <p className="mt-2 text-sm sm:text-base leading-relaxed text-white/60">
                                                {item.description}
                                            </p>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>

                        {/* Bottom Tactile 3D Action */}
                        <div className="mt-8 pt-6 border-t border-white/10 flex items-center justify-between" style={{ transform: "translateZ(20px)" }}>
                            <span className="text-xs font-semibold text-white/50">Ready to start?</span>
                            <a
                                href="#contact"
                                className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-gradient-to-b from-white to-slate-200 px-5 py-2.5 text-xs font-extrabold text-black transition-all duration-200 shadow-[0_4px_0_#94a3b8] hover:-translate-y-0.5 hover:shadow-[0_6px_0_#94a3b8] active:translate-y-0.5 active:shadow-[0_1px_0_#94a3b8]"
                            >
                                <MessageSquare className="h-4 w-4" />
                                <span>Let's Talk Project</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}

export default About;